# URL de conexão: Altere 'localhost:5432' se o seu banco estiver em outra porta,
# e altere 'db_calango' para o nome do banco de dados que você criou no Postgres.
spring.datasource.url=jdbc:postgresql://localhost:5432/db_calango
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
# 'update' faz o Hibernate criar as tabelas automaticamente se elas não existirem
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostra no console o comando SQL que o Java está executando (ótimo para desenvolvimento)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true